include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_use_package_imports
    - avoid_void_async
    - cancel_subscriptions
    - eol_at_end_of_file
    - prefer_const_declarations
    - prefer_double_quotes
    - prefer_final_locals
    - require_trailing_commas
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - use_named_constants
