name: likertshift
description: "App for the Likertshift project"
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
