name: likertshift
description: "App for the LikertShift project"
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  adaptive_theme: ^3.6.0
  archive: ^3.6.1
  flutter_blue_plus: ^1.34.4
  flutter_form_builder: ^9.5.0
  flutter_map: ^7.0.2
  flutter_map_compass: ^1.1.0
  flutter_translate: ^4.1.0
  form_builder_validators: ^11.0.0
  geolocator: ^13.0.1
  latlong2: ^0.9.1
  loading_animation_widget: ^1.3.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  record: ^5.2.0
  restart_app: ^1.3.2
  vector_math: ^2.1.4
  wakelock_plus: ^1.2.8

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/forms/
    - assets/locales/
    - assets/routes/
